name: My Custom Eclipse MicroProfile®
version: 0.2.21
description: My Custom Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
license: Apache-2.0
language: java
maintainers:
  - name: Steven Hung
    email: sghung@ca.ibm.com
    github-id: sghung
default-template: default
